/**
 * Phase 0 golden tests — deterministic synthesizer extraction.
 *
 * Contract being proven (docs/guardian-reasoning-service.md §7 Phase 0):
 * `synthesizeHeartbeatAdvisory` reproduces the heartbeat's original
 * `pickRecommendation` output **byte-for-byte** across live / partial-down /
 * all-down fixtures.
 *
 * The GOLDEN literals below were generated by extracting the original
 * (pre-Phase-0) `pickRecommendation` from the heartbeat at the commit that
 * introduced this module's extraction target (git HEAD at extraction time)
 * and executing it against the same fixtures this file defines. They are
 * therefore an INDEPENDENT freeze of the original behaviour: the shared
 * implementation is compared against recorded output, not against a copy of
 * itself. Any wording drift — a changed adjective, a different disclosure —
 * fails these tests.
 *
 * The heartbeat route's own honesty suite (guardian-heartbeat.test.ts) still
 * pins the route alias behaviourally from the app side; its assertions and
 * these literals describe the same fixtures.
 */

import { describe, expect, it } from 'vitest';
import {
  synthesizeHeartbeatAdvisory,
  toGuardianSignals,
  evaluateGates,
  type HeartbeatMarketSnapshot,
} from '../index';

const TS = '2026-09-05T00:00:00.000Z';

function snapshot(opts: {
  defillamaLive?: boolean;
  pools?: HeartbeatMarketSnapshot['defillama']['pools'];
  coingeckoLive?: boolean;
  bitcoin?: number | null;
  paxGold?: number | null;
  worldBankLive?: boolean;
  inflation?: number | null;
}): HeartbeatMarketSnapshot {
  return {
    defillama: {
      live: opts.defillamaLive ?? true,
      pools: opts.pools ?? [],
    },
    coingecko: {
      live: opts.coingeckoLive ?? true,
      bitcoin: opts.bitcoin ?? (opts.coingeckoLive === false ? null : 65432),
      pax_gold: opts.paxGold ?? (opts.coingeckoLive === false ? null : 2411),
    },
    worldBank: {
      live: opts.worldBankLive ?? true,
      current_inflation: opts.inflation ?? (opts.worldBankLive === false ? null : 4.2),
    },
    timestamp: TS,
  };
}

/**
 * Goldens generated from the ORIGINAL pre-extraction implementation
 * (`git show <extraction-base>:apps/web/pages/api/agent/guardian-heartbeat.ts`
 * → `pickRecommendation` executed against the identical fixtures).
 * Regenerate ONLY when a reasoning wording change is intentionally reviewed;
 * a diff here is an on-chain-text change and must be treated as such.
 */
const GOLDEN: Record<string, { action: string; targetToken: string; reasoning: string; confidence: number }> = {
  allLive: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cUSD',
    reasoning:
      'High inflation (4.2%) detected (World Bank CPI, live). Recommend cUSD savings position on Celo to preserve purchasing power. Inflation: 4.2% (World Bank CPI, live), BTC: $65,432 (CoinGecko, live), PAXG: $2,411 (CoinGecko, live), Top yield: Mento at 12.50% APY ($5.0M TVL, DeFiLlama, live).',
    confidence: 0.72,
  },
  highInflation: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cUSD',
    reasoning:
      'High inflation (7.8%) detected (World Bank CPI, live). Recommend cUSD savings position on Celo to preserve purchasing power. Inflation: 7.8% (World Bank CPI, live), BTC: $65,432 (CoinGecko, live), PAXG: $2,411 (CoinGecko, live).',
    confidence: 0.72,
  },
  coingeckoDown: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cUSD',
    reasoning:
      'High inflation (4.2%) detected (World Bank CPI, live). Recommend cUSD savings position on Celo to preserve purchasing power. Inflation: 4.2% (World Bank CPI, live), Top yield: Mento at 12.50% APY ($5.0M TVL, DeFiLlama, live). Sources unavailable this beat: CoinGecko prices — no fallback figures were used.',
    confidence: 0.72,
  },
  worldBankDownStrongYield: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'USDC',
    reasoning:
      'Attractive yield opportunity: Mento at 12.50% APY (DeFiLlama, live). Recommend USDC deployment on Arbitrum. BTC: $65,432 (CoinGecko, live), PAXG: $2,411 (CoinGecko, live), Top yield: Mento at 12.50% APY ($5.0M TVL, DeFiLlama, live). Sources unavailable this beat: World Bank CPI — no fallback figures were used.',
    confidence: 0.68,
  },
  allDown: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cEUR',
    reasoning:
      'No actionable live signal this beat — inflation not measured. Recommend holding the cEUR core; no fallback market figures were used.  Sources unavailable this beat: World Bank CPI, CoinGecko prices, DeFiLlama yields — no fallback figures were used.',
    confidence: 0.6,
  },
  stableRegime: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cEUR',
    reasoning:
      'Stable regime measured: inflation 2% (World Bank CPI, live). Recommend holding cEUR as inflation hedge. Inflation: 2% (World Bank CPI, live), BTC: $65,432 (CoinGecko, live), PAXG: $2,411 (CoinGecko, live).',
    confidence: 0.65,
  },
  weakYield: {
    action: 'ADVISORY_HEARTBEAT',
    targetToken: 'cEUR',
    reasoning:
      'No actionable live signal this beat — inflation not measured and yields below the 5% threshold. Recommend holding the cEUR core; no fallback market figures were used. BTC: $65,432 (CoinGecko, live), PAXG: $2,411 (CoinGecko, live), Top yield: Mento at 3.20% APY ($5.0M TVL, DeFiLlama, live). Sources unavailable this beat: World Bank CPI — no fallback figures were used.',
    confidence: 0.6,
  },
};

const FIXTURES: Record<string, HeartbeatMarketSnapshot> = {
  allLive: snapshot({ inflation: 4.2, pools: [{ protocol: 'Mento', apy: 12.5, tvl: 5_000_000 }] }),
  highInflation: snapshot({ inflation: 7.8 }),
  coingeckoDown: snapshot({
    inflation: 4.2,
    coingeckoLive: false,
    bitcoin: null,
    paxGold: null,
    pools: [{ protocol: 'Mento', apy: 12.5, tvl: 5_000_000 }],
  }),
  worldBankDownStrongYield: snapshot({
    worldBankLive: false,
    inflation: null,
    pools: [{ protocol: 'Mento', apy: 12.5, tvl: 5_000_000 }],
  }),
  allDown: snapshot({
    defillamaLive: false,
    coingeckoLive: false,
    bitcoin: null,
    paxGold: null,
    worldBankLive: false,
    inflation: null,
  }),
  stableRegime: snapshot({ inflation: 2.0 }),
  weakYield: snapshot({
    worldBankLive: false,
    inflation: null,
    pools: [{ protocol: 'Mento', apy: 3.2, tvl: 5_000_000 }],
  }),
};

describe('Phase 0 golden: shared synthesizer ≡ original heartbeat output (byte-identical)', () => {
  for (const [name, snap] of Object.entries(FIXTURES)) {
    it(`${name} — every field byte-identical to the frozen original`, () => {
      const actual = synthesizeHeartbeatAdvisory(snap);
      const golden = GOLDEN[name];

      expect(actual.reasoning).toBe(golden.reasoning);
      expect(actual.action).toBe(golden.action);
      expect(actual.targetToken).toBe(golden.targetToken);
      expect(actual.confidence).toBe(golden.confidence);
    });
  }

  it('fixture set matches the golden set (no orphan fixtures/goldens)', () => {
    expect(Object.keys(FIXTURES).sort()).toEqual(Object.keys(GOLDEN).sort());
  });

  it('all-down golden keeps the honesty invariants (no fabricated figures)', () => {
    // Belt-and-braces on the freeze itself: the recorded original must
    // already satisfy the honesty contract, so the golden can never become
    // the vehicle for re-importing a fabricated default.
    const g = GOLDEN.allDown;
    expect(g.reasoning).not.toContain('$');
    expect(g.reasoning).not.toContain('65,000');
    expect(g.reasoning).not.toContain('2,400');
    expect(g.reasoning).not.toContain('3.1');
    expect(g.reasoning).toContain('no fallback market figures were used');
  });
});

describe('toGuardianSignals — provenance-honest bundle mapping', () => {
  it('live figures map to live signals with sources', () => {
    const signals = toGuardianSignals(FIXTURES.allLive);
    const keys = signals.map((s) => s.key);
    expect(keys).toContain('inflation.us.cpi');
    expect(keys).toContain('price.btc');
    expect(keys).toContain('price.paxg');
    expect(keys).toContain('yield.stable.topApy');
    expect(signals.every((s) => s.live && s.capturedAt === TS)).toBe(true);
  });

  it('unavailable sources never become live signals', () => {
    const signals = toGuardianSignals(FIXTURES.allDown);
    expect(signals).toHaveLength(0);
  });

  it('live-but-empty yield read yields no yield signal (not an outage)', () => {
    const signals = toGuardianSignals(FIXTURES.stableRegime);
    const keys = signals.map((s) => s.key);
    expect(keys).toContain('inflation.us.cpi');
    expect(keys).not.toContain('yield.stable.topApy');
  });

  it('every mapped signal is live with a named source', () => {
    for (const signals of Object.values(FIXTURES).map(toGuardianSignals)) {
      expect(signals.every((s) => s.live && s.source.length > 0)).toBe(true);
    }
  });
});

describe('evaluateGates — Layer A floor (pure, shared across surfaces)', () => {
  const passingGate = { allowed: true };
  const decliningGate = { allowed: false, reason: 'daily_limit_reached', detail: 'over cap' };

  it('aggregates declines with stable reason codes', () => {
    const verdict = evaluateGates([() => passingGate, () => decliningGate], { signals: [] });
    expect(verdict).toEqual({ status: 'declined', reasons: ['daily_limit_reached'] });
  });

  it('all-passing gates are eligible with no reasons', () => {
    const verdict = evaluateGates([() => passingGate, () => passingGate], { signals: [] });
    expect(verdict).toEqual({ status: 'eligible', reasons: [] });
  });
});
