// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title RecommendationLedger
 * @notice Immutable on-chain record of every AI recommendation generated by DiversiFi.
 *
 * Each entry links:
 *   - User address (who received the recommendation)
 *   - Recommendation action + reasoning (e.g. "SWAP USDC→USDY")
 *   - 0G Storage evidence CID (proof of AI reasoning + source data)
 *   - 0G Serving model hash (which AI model generated the advice)
 *   - Settlement tx hash (if nanopayment was made)
 *   - Timestamp
 *
 * 0G APAC Hackathon Narrative:
 *   "Every recommendation is verifiably traced from 0G Serving inference
 *    → 0G Storage evidence → 0G Chain immutable record."
 */
contract RecommendationLedger {
    // ====================================================================
    // TYPES
    // ====================================================================

    struct Recommendation {
        address user;
        string action;           // SWAP | HOLD | REBALANCE | BRIDGE
        string targetToken;      // e.g. "USDY", "PAXG"
        string reasoning;        // Full AI-generated reasoning
        string evidenceCid;      // 0G Storage CID for evidence bundle
        string servingModel;     // 0G Serving model ID (e.g. "deepseek-v4-pro")
        string settlementTxHash; // Arc x402 settlement tx hash (if applicable)
        uint256 timestamp;       // Block timestamp
        uint256 confidence;      // AI confidence score (0-10000, basis points)
    }

    // ====================================================================
    // STATE
    // ====================================================================

    /// @notice Incremental ID for each recommendation
    uint256 public totalRecommendations;

    /// @notice All recommendations, indexed by ID
    mapping(uint256 => Recommendation) public recommendations;

    /// @notice Recommendations by user
    mapping(address => uint256[]) public recommendationsByUser;

    /// @notice Authorized agent addresses that can record recommendations
    mapping(address => bool) public authorizedAgents;

    /// @notice Contract owner (admin)
    address public owner;

    // ====================================================================
    // EVENTS
    // ====================================================================

    event RecommendationRecorded(
        uint256 indexed id,
        address indexed user,
        string action,
        string targetToken,
        string evidenceCid,
        string servingModel,
        uint256 confidence,
        uint256 timestamp
    );

    event AgentAuthorized(address indexed agent, bool authorized);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    // ====================================================================
    // MODIFIERS
    // ====================================================================

    modifier onlyOwner() {
        require(msg.sender == owner, "Not contract owner");
        _;
    }

    // ====================================================================
    // CONSTRUCTOR
    // ====================================================================

    constructor() {
        owner = msg.sender;
        // Deployer is automatically authorized
        authorizedAgents[msg.sender] = true;
    }

    // ====================================================================
    // ADMIN FUNCTIONS
    // ====================================================================

    /**
     * @notice Authorize or revoke an agent address
     */
    function setAgentAuthorization(address agent, bool authorized) external onlyOwner {
        authorizedAgents[agent] = authorized;
        emit AgentAuthorized(agent, authorized);
    }

    /**
     * @notice Transfer contract ownership
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "New owner cannot be zero");
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    // ====================================================================
    // CORE FUNCTIONS
    // ====================================================================

    /**
     * @notice Record a recommendation on-chain
     * @param user The user who received the recommendation
     * @param action The recommended action (SWAP, HOLD, REBALANCE, BRIDGE)
     * @param targetToken The target token for the action (empty string if HOLD)
     * @param reasoning Full AI-generated reasoning text
     * @param evidenceCid 0G Storage CID of evidence bundle
     * @param servingModel 0G Serving model ID used for inference
     * @param settlementTxHash Arc x402 settlement tx hash (can be empty)
     * @param confidence Confidence score in basis points (0-10000)
     * @return The ID of the recorded recommendation
     */
    function recordRecommendation(
        address user,
        string calldata action,
        string calldata targetToken,
        string calldata reasoning,
        string calldata evidenceCid,
        string calldata servingModel,
        string calldata settlementTxHash,
        uint256 confidence
    ) external returns (uint256) {
        // Allow: authorized agents, the contract owner, or the user recording about themselves
        require(
            authorizedAgents[msg.sender] ||
            msg.sender == owner ||
            msg.sender == user,
            "Not authorized to record"
        );
        require(user != address(0), "User cannot be zero address");
        require(bytes(action).length > 0, "Action required");
        require(confidence <= 10000, "Confidence max 10000 bps");

        uint256 id = ++totalRecommendations;

        recommendations[id] = Recommendation({
            user: user,
            action: action,
            targetToken: targetToken,
            reasoning: reasoning,
            evidenceCid: evidenceCid,
            servingModel: servingModel,
            settlementTxHash: settlementTxHash,
            timestamp: block.timestamp,
            confidence: confidence
        });

        recommendationsByUser[user].push(id);

        emit RecommendationRecorded(
            id,
            user,
            action,
            targetToken,
            evidenceCid,
            servingModel,
            confidence,
            block.timestamp
        );

        return id;
    }

    // ====================================================================
    // VIEW FUNCTIONS
    // ====================================================================

    /**
     * @notice Get a recommendation by ID
     */
    function getRecommendation(uint256 id) external view returns (Recommendation memory) {
        require(id > 0 && id <= totalRecommendations, "Invalid recommendation ID");
        return recommendations[id];
    }

    /**
     * @notice Get all recommendation IDs for a user
     */
    function getUserRecommendationIds(address user) external view returns (uint256[] memory) {
        return recommendationsByUser[user];
    }

    /**
     * @notice Get paginated recommendations for a user
     */
    function getUserRecommendations(
        address user,
        uint256 offset,
        uint256 limit
    ) external view returns (Recommendation[] memory results, uint256 total) {
        uint256[] memory ids = recommendationsByUser[user];
        total = ids.length;

        if (offset >= total) {
            return (new Recommendation[](0), total);
        }

        uint256 end = offset + limit;
        if (end > total) {
            end = total;
        }

        uint256 resultCount = end - offset;
        results = new Recommendation[](resultCount);

        for (uint256 i = 0; i < resultCount; i++) {
            results[i] = recommendations[ids[offset + i]];
        }

        return (results, total);
    }

    /**
     * @notice Get the total number of recommendations for a user
     */
    function getUserRecommendationCount(address user) external view returns (uint256) {
        return recommendationsByUser[user].length;
    }

    /**
     * @notice Check if a recommendation exists
     */
    function recommendationExists(uint256 id) external view returns (bool) {
        return id > 0 && id <= totalRecommendations && bytes(recommendations[id].action).length > 0;
    }
}
