// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/access/Ownable2Step.sol";

/**
 * @title RecommendationLedger
 * @notice Immutable on-chain record of every AI recommendation generated by DiversiFi.
 *
 * Each entry links:
 *   - User address (who received the recommendation)
 *   - Recommendation action + target token (e.g. "SWAP USDC→USDY")
 *   - 0G Storage evidence CID (proof of AI reasoning + source data)
 *   - keccak256 hash of the full reasoning (cheap on-chain commitment)
 *   - 0G Serving model hash (which AI model generated the advice)
 *   - Settlement tx hash (if nanopayment was made)
 *   - Timestamp
 *
 * The full reasoning text lives off-chain in 0G Storage; only its hash is
 * recorded on-chain to keep the ledger cheap and scalable while preserving
 * verifiability.
 */
contract RecommendationLedger is Ownable2Step {
    // ====================================================================
    // TYPES
    // ====================================================================

    struct Recommendation {
        address user;
        string action; // SWAP | HOLD | REBALANCE | BRIDGE
        string targetToken; // e.g. "USDY", "PAXG"
        bytes32 reasoningHash; // keccak256(full reasoning) — on-chain commitment
        string evidenceCid; // 0G Storage CID for evidence bundle
        string servingModel; // 0G Serving model ID (e.g. "deepseek-v4-pro")
        string settlementTxHash; // Arc x402 settlement tx hash (if applicable)
        uint256 timestamp; // Block timestamp
        uint256 confidence; // AI confidence score (0-10000, basis points)
    }

    // ====================================================================
    // STATE
    // ====================================================================

    /// @notice Incremental ID for each recommendation
    uint256 public totalRecommendations;

    /// @notice All recommendations, indexed by ID
    mapping(uint256 => Recommendation) public recommendations;

    /// @notice Recommendations by user
    mapping(address => uint256[]) public recommendationsByUser;

    /// @notice Authorized agent addresses that can record recommendations
    mapping(address => bool) public authorizedAgents;

    // ====================================================================
    // EVENTS
    // ====================================================================

    event RecommendationRecorded(
        uint256 indexed id,
        address indexed user,
        string action,
        string targetToken,
        bytes32 reasoningHash,
        string evidenceCid,
        string servingModel,
        uint256 confidence,
        uint256 timestamp
    );

    event AgentAuthorized(address indexed agent, bool authorized);

    // ====================================================================
    // ERRORS
    // ====================================================================

    error UnauthorizedRecorder(address caller);
    error ZeroAddress();
    error EmptyAction();
    error ConfidenceTooHigh(uint256 confidence);
    error InvalidRecommendationId(uint256 id);

    // ====================================================================
    // CONSTRUCTOR
    // ====================================================================

    constructor() Ownable(msg.sender) {
        // Deployer is automatically authorized
        authorizedAgents[msg.sender] = true;
    }

    // ====================================================================
    // ADMIN FUNCTIONS
    // ====================================================================

    /**
     * @notice Authorize or revoke an agent address
     */
    function setAgentAuthorization(address agent, bool authorized) external onlyOwner {
        if (agent == address(0)) revert ZeroAddress();
        authorizedAgents[agent] = authorized;
        emit AgentAuthorized(agent, authorized);
    }

    // ====================================================================
    // CORE FUNCTIONS
    // ====================================================================

    /**
     * @notice Record a recommendation on-chain
     * @param user The user who received the recommendation
     * @param action The recommended action (SWAP, HOLD, REBALANCE, BRIDGE)
     * @param targetToken The target token for the action (empty string if HOLD)
     * @param reasoningHash keccak256 of the full AI reasoning text
     * @param evidenceCid 0G Storage CID of evidence bundle
     * @param servingModel 0G Serving model ID used for inference
     * @param settlementTxHash Arc x402 settlement tx hash (can be empty)
     * @param confidence Confidence score in basis points (0-10000)
     * @return The ID of the recorded recommendation
     */
    function recordRecommendation(
        address user,
        string calldata action,
        string calldata targetToken,
        bytes32 reasoningHash,
        string calldata evidenceCid,
        string calldata servingModel,
        string calldata settlementTxHash,
        uint256 confidence
    ) external returns (uint256) {
        // Allow: authorized agents, the contract owner, or the user recording about themselves
        if (!authorizedAgents[msg.sender] && msg.sender != owner() && msg.sender != user) {
            revert UnauthorizedRecorder(msg.sender);
        }
        if (user == address(0)) revert ZeroAddress();
        if (bytes(action).length == 0) revert EmptyAction();
        if (confidence > 10000) revert ConfidenceTooHigh(confidence);

        uint256 id = ++totalRecommendations;

        recommendations[id] = Recommendation({
            user: user,
            action: action,
            targetToken: targetToken,
            reasoningHash: reasoningHash,
            evidenceCid: evidenceCid,
            servingModel: servingModel,
            settlementTxHash: settlementTxHash,
            timestamp: block.timestamp,
            confidence: confidence
        });

        recommendationsByUser[user].push(id);

        emit RecommendationRecorded(
            id, user, action, targetToken, reasoningHash, evidenceCid, servingModel, confidence, block.timestamp
        );

        return id;
    }

    // ====================================================================
    // VIEW FUNCTIONS
    // ====================================================================

    /**
     * @notice Get a recommendation by ID
     */
    function getRecommendation(uint256 id) external view returns (Recommendation memory) {
        if (id == 0 || id > totalRecommendations) revert InvalidRecommendationId(id);
        return recommendations[id];
    }

    /**
     * @notice Get all recommendation IDs for a user
     */
    function getUserRecommendationIds(address user) external view returns (uint256[] memory) {
        return recommendationsByUser[user];
    }

    /**
     * @notice Get paginated recommendations for a user
     */
    function getUserRecommendations(address user, uint256 offset, uint256 limit)
        external
        view
        returns (Recommendation[] memory results, uint256 total)
    {
        uint256[] memory ids = recommendationsByUser[user];
        total = ids.length;

        if (offset >= total) {
            return (new Recommendation[](0), total);
        }

        uint256 end = offset + limit;
        if (end > total) {
            end = total;
        }

        uint256 resultCount = end - offset;
        results = new Recommendation[](resultCount);

        for (uint256 i = 0; i < resultCount; i++) {
            results[i] = recommendations[ids[offset + i]];
        }

        return (results, total);
    }

    /**
     * @notice Get the total number of recommendations for a user
     */
    function getUserRecommendationCount(address user) external view returns (uint256) {
        return recommendationsByUser[user].length;
    }

    /**
     * @notice Check if a recommendation exists
     */
    function recommendationExists(uint256 id) external view returns (bool) {
        return id > 0 && id <= totalRecommendations && bytes(recommendations[id].action).length > 0;
    }
}
